#! /usr/bin/env python

import argparse
import os
import sys

CONDA_CHANNEL = "ad-testing/label/py313"
OUTPUT_DIR = "/tmp/py313t-recipes"


def feedstock_path(feedstock):
    if os.path.isdir(feedstock):
        path = feedstock
    elif os.path.isdir(feedstock + '-feedstock'):
        path = feedstock + '-feedstock'
    else:
        return False
    if not os.path.isfile(os.path.join(path, 'recipe', 'meta.yaml')):
        return False
    return path


def build(feedstock):
    print("Building", feedstock)
    path = feedstock_path(feedstock)


def test(feedstock):
    print("Testing", feedstock)
    path = feedstock_path(feedstock)


def build_and_test(feedstock):
    print("Building and testing", feedstock)
    path = feedstock_path(feedstock)


if __name__ == "__main__":
    argparser = argparse.ArgumentParser(
        prog='build',
        description='Multi-ABI (GIL and free-threading} build tool for Conda feedstocks')
    argparser.add_argument(
        '-v',
        '--verbose',
        action='store_true',
        help = 'Show build and test output')
    build_test_group = argparser.add_mutually_exclusive_group()
    build_test_group.add_argument(
        '-b',
        '--build',
        action='store_true',
        help = 'Only build feedstock(s)')
    build_test_group.add_argument(
        '-t',
        '--test',
        action='store_true',
        help = 'Only test feedstock(s)')
    build_test_group.add_argument(
        '-d',
        '--build-and-test',
        action='store_true',
        help = '''Build and test each feedstock in a single pass like conda-build would do. When
            building feedstocks, the default is they will first be all built in the order passed on
            the command-line, then all tested in the same order. This is done to automaticaly work
            around some circular dependencies. Use this option to revert to the default conda-build
            behavior.''')
    argparser.add_argument(
        '-m',
        '--variant',
        nargs = 1,
        action = 'append',
        help = 'Add a variant config file (may be passed multiple times)')
    argparser.add_argument(
        'feedstocks',
        nargs = '+',
        help = 'List of feedstocks to build and/or test')
    args = argparser.parse_args()
    print(args)

    # Check we can find all feedstocks first to make sure we don't start building for nothing
    missing_feedstocks = False
    for feedstock in args.feedstocks:
        if not feedstock_path(feedstock):
            print("Can't find feedstock at", feedstock, "or", feedstock+'-feedstock')
            missing_feedstocks = True
    if missing_feedstocks:
        sys.exit("Couldn't find all feedstocks")

    # Build feedstocks
    if not args.test and not args.build_and_test:
        for feedstock in args.feedstocks:
            build(feedstock)

    # Test feedstocks
    if not args.build and not args.build_and_test:
        for feedstock in args.feedstocks:
            test(feedstock)

    # Build and test feedstocks in a single pass like conda-build would do
    if args.build_and_test:
        for feedstock in args.feedstocks:
            build_and_test(feedstock)
